import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Sparkles, Send, Loader2, AlertCircle, RefreshCw, FileText, Check, PhoneCall, Award } from "lucide-react";
import { DiagnosisResult } from "../types";

export default function AIDiagnosisSection() {
  const [form, setForm] = useState({
    companyName: "",
    totalEmployees: "",
    currentDisabledEmployees: "",
    managerName: "",
    managerContact: "",
    managerEmail: "",
  });

  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<DiagnosisResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (
      !form.companyName ||
      !form.totalEmployees ||
      !form.managerName ||
      !form.managerContact ||
      !form.managerEmail
    ) {
      setError("필수 입력 항목(*)을 모두 기입해 주세요.");
      return;
    }

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const response = await fetch("/api/diagnose", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          companyName: form.companyName,
          totalEmployees: parseInt(form.totalEmployees, 10),
          currentDisabledEmployees: parseInt(form.currentDisabledEmployees, 10) || 0,
          managerName: form.managerName,
          managerContact: form.managerContact,
          managerEmail: form.managerEmail,
        }),
      });

      if (!response.ok) {
        throw new Error("서버에서 진단서를 생성하는 중 실패했습니다.");
      }

      const data = await response.json();
      setResult(data);

      // Save inquiry to localStorage for Admin Dashboard review
      try {
        const saved = localStorage.getItem("bene_people_inquiries");
        const list = saved ? JSON.parse(saved) : [];
        const newInquiry = {
          id: `inq-${Date.now()}`,
          companyName: form.companyName,
          totalEmployees: parseInt(form.totalEmployees, 10),
          currentDisabledEmployees: parseInt(form.currentDisabledEmployees, 10) || 0,
          managerName: form.managerName,
          managerContact: form.managerContact,
          managerEmail: form.managerEmail,
          date: new Date().toISOString().split("T")[0],
          savingsYearly: data.savingsYearly || 0,
          status: "접수대기",
        };
        list.unshift(newInquiry);
        localStorage.setItem("bene_people_inquiries", JSON.stringify(list));
      } catch (storageError) {
        console.warn("Could not save inquiry to local storage:", storageError);
      }
    } catch (err: any) {
      console.error(err);
      setError("AI 진단서 생성 중 연결 실패가 발생했습니다. 잠시 후 다시 시도해 주세요.");
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setForm({
      companyName: "",
      totalEmployees: "",
      currentDisabledEmployees: "",
      managerName: "",
      managerContact: "",
      managerEmail: "",
    });
    setResult(null);
  };

  // Helper function to render markdown generated by Gemini safely into UI
  const parseMarkdownToReact = (text: string) => {
    return text.split("\n").map((line, idx) => {
      const trimmed = line.trim();
      if (trimmed.startsWith("###")) {
        return (
          <h4 key={idx} className="text-base sm:text-lg font-bold text-brand-green mt-6 mb-3 border-l-4 border-brand-accent pl-2.5">
            {trimmed.replace("###", "").trim()}
          </h4>
        );
      }
      if (trimmed.startsWith("##")) {
        return (
          <h3 key={idx} className="text-lg sm:text-xl font-black text-brand-green mt-8 mb-4 border-b border-gray-100 pb-2">
            {trimmed.replace("##", "").trim()}
          </h3>
        );
      }
      if (trimmed.startsWith("#")) {
        return (
          <h2 key={idx} className="text-xl sm:text-2xl font-black text-brand-green mt-10 mb-4 text-center">
            {trimmed.replace("#", "").trim()}
          </h2>
        );
      }
      if (trimmed.startsWith("-") || trimmed.startsWith("*")) {
        // Handle bolding within bullet point e.g., **text**
        const rawContent = trimmed.replace(/^[-*]\s*/, "").trim();
        return (
          <li key={idx} className="text-xs sm:text-sm text-gray-600 ml-4 list-disc my-1.5 leading-relaxed font-sans">
            {renderLineWithBolding(rawContent)}
          </li>
        );
      }
      if (trimmed === "") {
        return <div key={idx} className="h-2"></div>;
      }
      return (
        <p key={idx} className="text-xs sm:text-sm text-gray-700 leading-relaxed my-2 font-sans">
          {renderLineWithBolding(trimmed)}
        </p>
      );
    });
  };

  // Safe inner line bold parser for **bold** format
  const renderLineWithBolding = (line: string) => {
    const parts = line.split(/\*\*(.*?)\*\*/g);
    if (parts.length === 1) return line;
    return parts.map((part, i) => i % 2 === 1 ? <strong key={i} className="text-brand-green font-bold">{part}</strong> : part);
  };

  return (
    <section id="ai-diagnosis" className="py-24 bg-brand-green text-white relative overflow-hidden">
      {/* Background decorations */}
      <div className="absolute top-0 left-0 w-96 h-96 bg-[#0D5C4E] rounded-full filter blur-[100px] opacity-30 -ml-20 -mt-20"></div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <span className="font-mono text-xs uppercase tracking-widest text-brand-accent px-3 py-1 bg-white/10 rounded-full font-bold">
            AI CONSULTATION SYSTEM
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight mt-4 text-white">
            우리 회사의 <span className="text-brand-accent">장애인 고용 부담금 분석</span>
          </h2>
          <p className="text-gray-300 mt-4 text-sm sm:text-base leading-relaxed">
            회사 규모와 현재 고용 상태를 기재해 보세요. Google Gemini AI가 실시간 분석하여 실제 수억원 상당의 리스크 예방 및 전용 제안서를 단 3초 만에 무상으로 자동 추출해 드립니다.
          </p>
        </div>

        <div className="max-w-5xl mx-auto">
          <AnimatePresence mode="wait">
            {!result ? (
              /* Diagnosis Entry Form */
              <motion.div
                key="form"
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -15 }}
                className="bg-white text-[#1A2E2A] rounded-2xl shadow-2xl p-6 sm:p-10 border border-gray-100"
              >
                <form onSubmit={handleSubmit} className="space-y-6">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* Field 1: Company Name */}
                    <div>
                      <label className="block text-xs sm:text-sm font-bold text-gray-700 mb-2">
                        회사명 (귀사명) <span className="text-red-500">*</span>
                      </label>
                      <input
                        type="text"
                        name="companyName"
                        required
                        value={form.companyName}
                        onChange={handleChange}
                        placeholder="예: (주)베네피플전자"
                        className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-brand-lightgreen focus:border-transparent outline-none text-xs sm:text-sm font-medium transition"
                        disabled={loading}
                      />
                    </div>

                    {/* Field 2: Total Employees */}
                    <div>
                      <label className="block text-xs sm:text-sm font-bold text-gray-700 mb-2">
                        전체 상시 근로자 수 (명) <span className="text-red-500">*</span>
                      </label>
                      <input
                        type="number"
                        name="totalEmployees"
                        required
                        min="1"
                        value={form.totalEmployees}
                        onChange={handleChange}
                        placeholder="예: 320"
                        className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-brand-lightgreen focus:border-transparent outline-none text-xs sm:text-sm font-medium transition"
                        disabled={loading}
                      />
                    </div>

                    {/* Field 3: Current Disabled */}
                    <div>
                      <label className="block text-xs sm:text-sm font-bold text-gray-700 mb-2">
                        현재 고용 중인 장애인 수 (명) <span className="text-red-500">*</span>
                      </label>
                      <input
                        type="number"
                        name="currentDisabledEmployees"
                        required
                        min="0"
                        value={form.currentDisabledEmployees}
                        onChange={handleChange}
                        placeholder="고용 중이 아닐 경우 0 입력"
                        className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-brand-lightgreen focus:border-transparent outline-none text-xs sm:text-sm font-medium transition"
                        disabled={loading}
                      />
                    </div>

                    {/* Field 4: Manager Name */}
                    <div>
                      <label className="block text-xs sm:text-sm font-bold text-gray-700 mb-2">
                        담당자 이름 <span className="text-red-500">*</span>
                      </label>
                      <input
                        type="text"
                        name="managerName"
                        required
                        value={form.managerName}
                        onChange={handleChange}
                        placeholder="예: 홍길동 인사팀장"
                        className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-brand-lightgreen focus:border-transparent outline-none text-xs sm:text-sm font-medium transition"
                        disabled={loading}
                      />
                    </div>

                    {/* Field 5: Contact */}
                    <div>
                      <label className="block text-xs sm:text-sm font-bold text-gray-700 mb-2">
                        담당자 연락처 <span className="text-red-500">*</span>
                      </label>
                      <input
                        type="tel"
                        name="managerContact"
                        required
                        value={form.managerContact}
                        onChange={handleChange}
                        placeholder="예: 010-1234-5678"
                        className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-brand-lightgreen focus:border-transparent outline-none text-xs sm:text-sm font-medium transition"
                        disabled={loading}
                      />
                    </div>

                    {/* Field 6: Email */}
                    <div>
                      <label className="block text-xs sm:text-sm font-bold text-gray-700 mb-2">
                        이메일 주소 <span className="text-red-500">*</span>
                      </label>
                      <input
                        type="email"
                        name="managerEmail"
                        required
                        value={form.managerEmail}
                        onChange={handleChange}
                        placeholder="진단 결과를 발송할 이메일 주소"
                        className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-brand-lightgreen focus:border-transparent outline-none text-xs sm:text-sm font-medium transition"
                        disabled={loading}
                      />
                    </div>
                  </div>

                  {error && (
                    <div className="bg-red-50 border border-red-100 p-4 rounded-xl text-red-700 text-xs sm:text-sm flex items-center gap-2.5">
                      <AlertCircle className="w-5 h-5 text-red-600 shrink-0" />
                      <span>{error}</span>
                    </div>
                  )}

                  <div className="pt-4">
                    <button
                      type="submit"
                      disabled={loading}
                      className="w-full bg-[#EBB63F] text-brand-green font-bold text-sm sm:text-base py-4 rounded-xl shadow-lg hover:bg-amber-400 active:scale-[0.99] transition flex items-center justify-center gap-2.5 cursor-pointer disabled:opacity-50"
                    >
                      {loading ? (
                        <>
                          <Loader2 className="w-5 h-5 animate-spin" />
                          <span>Google Gemini AI가 맞춤 제안서를 분석 중입니다...</span>
                        </>
                      ) : (
                        <>
                          <Sparkles className="w-5 h-5" />
                          <span>⚡ AI 정밀 진단 즉시 실행 및 제안서 수령</span>
                        </>
                      )}
                    </button>
                    <p className="text-[10px] text-gray-400 text-center mt-3 leading-relaxed">
                      ※ 당사 개인정보 처리방침에 근거하여 입력하신 자료는 1:1 진단 목적 외에 전혀 보존되거나 유출되지 않으니 안심하세요.
                    </p>
                  </div>
                </form>
              </motion.div>
            ) : (
              /* Diagnosis Report Output */
              <motion.div
                key="result"
                initial={{ opacity: 0, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.98 }}
                className="bg-white text-[#1A2E2A] rounded-2xl shadow-2xl overflow-hidden border border-gray-100"
              >
                {/* Header Banner */}
                <div className="bg-brand-green p-6 sm:p-8 text-white flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                  <div>
                    <span className="text-[10px] font-mono tracking-widest text-brand-accent uppercase bg-white/10 px-2.5 py-1 rounded">
                      Analysis Document Generated
                    </span>
                    <h3 className="text-xl sm:text-2xl font-black mt-2">
                      {form.companyName} 전용 고용 진단서
                    </h3>
                  </div>
                  <button
                    onClick={handleReset}
                    className="bg-white/10 hover:bg-white/20 border border-white/10 text-xs font-bold px-4 py-2 rounded-lg transition flex items-center gap-1.5 self-stretch sm:self-auto justify-center"
                  >
                    <RefreshCw className="w-4 h-4" /> 다시 계산하기
                  </button>
                </div>

                {/* Dashboard Stats Panel */}
                <div className="grid grid-cols-2 md:grid-cols-4 border-b border-gray-100">
                  <div className="p-4 sm:p-6 text-center border-r border-b md:border-b-0 border-gray-100">
                    <span className="text-[10px] sm:text-xs text-gray-400 block font-medium">법정 의무고용 (3.1%)</span>
                    <span className="text-xl sm:text-2xl font-black text-brand-green mt-1 block font-mono">
                      {result.requiredDisabledCount}명
                    </span>
                  </div>
                  <div className="p-4 sm:p-6 text-center border-r border-b md:border-b-0 border-gray-100">
                    <span className="text-[10px] sm:text-xs text-gray-400 block font-medium">현재 부족 인원</span>
                    <span className="text-xl sm:text-2xl font-black text-red-500 mt-1 block font-mono">
                      {result.shortage}명
                    </span>
                  </div>
                  <div className="p-4 sm:p-6 text-center border-r border-gray-100">
                    <span className="text-[10px] sm:text-xs text-gray-400 block font-medium">연간 벌금 부담액</span>
                    <span className="text-xl sm:text-2xl font-black text-red-600 mt-1 block font-mono">
                      ₩{result.pureFineYearly.toLocaleString()}
                    </span>
                  </div>
                  <div className="p-4 sm:p-6 text-center">
                    <span className="text-[10px] sm:text-xs text-gray-400 block font-medium">연간 예산 절감액</span>
                    <span className="text-xl sm:text-2xl font-black text-emerald-600 mt-1 block font-mono">
                      ₩{result.savingsYearly.toLocaleString()}
                    </span>
                  </div>
                </div>

                {/* Main Gemini Analysis Report */}
                <div className="p-6 sm:p-8 space-y-4 bg-gray-50/50 border-b border-gray-100 max-h-[500px] overflow-y-auto no-scrollbar font-sans">
                  {parseMarkdownToReact(result.geminiReport)}
                </div>

                {/* Post Consultation Action banner */}
                <div className="p-6 sm:p-8 bg-[#EBB63F]/10 flex flex-col sm:flex-row items-center justify-between gap-6">
                  <div className="flex items-start gap-3.5">
                    <div className="w-10 h-10 rounded-full bg-[#EBB63F] flex items-center justify-center text-brand-green shrink-0 shadow-sm mt-0.5">
                      <PhoneCall className="w-5 h-5" />
                    </div>
                    <div>
                      <h4 className="font-extrabold text-[#1A2E2A] text-sm sm:text-base">
                        전문 노무 컨설턴트 1:1 무료 유선 상담 안내
                      </h4>
                      <p className="text-xs text-gray-600 mt-1 leading-relaxed">
                        Gemini AI 진단 내용을 토대로 베네피플의 전문 수석 공인노무사 및 인사 실무 컨설턴트가 24시간 내 유선 브리핑을 지원해 드립니다.
                      </p>
                    </div>
                  </div>
                  <a
                    href={`tel:02-1234-5678`}
                    className="bg-brand-green text-white font-bold text-xs sm:text-sm px-6 py-3.5 rounded-xl shadow-md hover:bg-brand-lightgreen transition self-stretch sm:self-auto text-center"
                  >
                    상담 예약 확정
                  </a>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </section>
  );
}
